### ISSUE TITLE
Page hangs on load after being logged in.

### ISSUE THREAD

**Issue by oxi** [dev-rke/Codiad-ToDo#2] opened 2016-03-01 07:57 UTC
https://github.com/Codiad/Codiad/issues/897

**Comment by dev-rke** [comment] 2016-03-02 14:27
As i am not using Codiad anymore i need to install it and need to understand, what they changed in their application. I'll give it a try on the weekend, maybe it's just a little change in initialization.
Do you get any javascript errors in the web developer console (press CTRL+F12 in Chrome or FF to open it)?

**Comment by oxi** [comment] 2016-03-03 10:45
Yes, I got one error:
Uncaught TypeError: Cannot read property 'split' of undefined

**Comment by dev-rke** [comment] 2016-03-18 00:41
Sorry, hadn't much time the last days.
I cannot reproduce your error.
Using Codiad 2.7.2 from git master branch works perfectly fine with Codiad-ToDo-Plugin.
Will it work if you install only Codiad-ToDo and disable all other plugins?

Can you provide further information (browser, operating system, conflicting plugins).

**Comment by oxi** [comment] 2016-03-22 09:19
Even if everything else is disabled, it does not work and the error appeared.

Tryed with Windows 10, Debian 8, Kubuntu with the google chrome 48.0.2564.109 (64-bit)

**Comment by dev-rke** [comment] 2016-03-23 00:09
That is bad.
Can you please provide a screenshot of the full error message from developer tools? 
I need the exact line of code which throws the error.
Can you also please provide the steps you do when using the application?
Example:

1. Login
1. Project is opened
1. File xyz.js opens automatically due to last session etc.

**Comment by oxi** [comment] 2016-03-23 08:27
Here is the screenshot. The error in red will only appear once the plugin is activated:
![bildschirmfoto1](https://cloud.githubusercontent.com/assets/1921347/13979462/fa8b6d38-f0d8-11e5-85ce-23d50c6e4211.png)
![bildschirmfoto2](https://cloud.githubusercontent.com/assets/1921347/13979542/7b62d072-f0d9-11e5-9673-57fb59d6cf82.png)


It does not matter which file is opened. The error event always occurs.
1. Login
2. Last Projekt is Open
3. Three Files are opened from the last session.
4. Page hangs

**Comment by dev-rke** [comment] 2016-03-23 23:08
Ok seems Content isn't an empty string.
Does it work if no files are opened from last session?
E.g. close all files, log out and log in again.

**Comment by oxi** [comment] 2016-03-24 07:26
Ok, when I close all Files, install the Plugin and reopen the files the error no longer appears.

But when I refresh the Page, the same error appears.

It looks like that if content at startup is not empty, the error occurs

**Comment by dev-rke** [comment] 2016-03-25 21:39
What do you mean with "refresh the Page"?
Have you tried reloading the plugin without browser cache using CTRL+F5?
I tried it with Chromium 49 and Firefox 45 with Ubuntu 14.04, can't reproduce your error.
I also uninstalled all other plugins, still cannot reproduce it.
Do you really use the latest Codiad version (Codiad v2.7.2)?

**Comment by oxi** [comment] 2016-03-29 12:47
> What do you mean with "refresh the Page"?

I mean, that I reopen the Page in a new Browser-Session.

> Have you tried reloading the plugin without browser cache using CTRL+F5?
Yes

> I tried it with Chromium 49 and Firefox 45 with Ubuntu 14.04, can't reproduce your error.
Google Chrome 48.0.2564.109 (64-bit)

> Do you really use the latest Codiad version (Codiad v2.7.2)?
Yes

it may rests against the web server (software)?

**Comment by dev-rke** [comment] 2016-03-30 21:51
> I mean, that I reopen the Page in a new Browser-Session.

Hm. So it works when you reload the page using CTRL+F5?
And it works not, when you reload the page by closing the current browser and reopen the browser again?
This sounds a bit like a caching problem for me.
Do you have access to the apache server configuration files?
Can you provide a screenshot of the http headers of the Codiad-ToDo-init.js file in the network tab (i am interested in the cache settings of your webserver) when it does not work.

**Comment by oxi** [comment] 2016-04-04 05:13
> Hm. So it works when you reload the page using CTRL+F5?

No, I could better explain it that way. It does not work on any way.

**Comment by dev-rke** [comment] 2016-04-04 14:15
Ok, can you ensure you have the latest codiad version installed (v2.7.2)?

**Comment by oxi** [comment] 2016-04-05 13:40
Yes

**Comment by dev-rke** [comment] 2016-04-06 14:29
Ok, as seen here, the getContent method returns nothing if there is no "active" editor:
https://github.com/Codiad/Codiad/blob/master/components/editor/init.js

This means my further code fails.
I try to fix this, hopefully today, otherwise on the weekend.

**Comment by dev-rke** [comment] 2016-04-06 21:21
Ok, tried to fix it, but i can still not reproduce your error. 
New Codiad-ToDo version is v0.1.1, maybe it takes some hours until it will be listed in codiad marketplace.

**Comment by dev-rke** [comment] 2016-04-09 21:12
@oxi: does it work?

**Comment by oxi** [comment] 2016-04-14 11:28
Sorry for the delay.
The Initial Error was fixed and the Page reloads.

But a new error at the console:
> init.coffee:61 Uncaught TypeError: Cannot read property 'getSession' of null

**Comment by dev-rke** [comment] 2016-04-14 14:32
I am wondering, why you havn't an active editor item.
The last fix just was a workaround, it is still unclear why the error occured in your environment.
Can you please try using different browsers to see if the problem persist?
Which other plugins are installed in Codiad?

**Comment by dev-rke** [comment] 2016-04-17 19:59
Do you use multiple editor panes?

**Comment by dev-rke** [comment] 2016-04-17 20:27
@oxi
I can also reproduce your first error when i enable multi panes (split editor window horizontally).
I fixed the behaviour. New version is 0.1.2.
This was kind of a crazy bug, because i never used multi pane support of codiad.
Please test it and give me some feedback.
Thank you.

**Comment by oxi** [comment] 2016-04-19 09:59
Ok, I will test this tomorrow.

**Comment by oxi** [comment] 2016-04-21 18:11
Ok, I don't use multiple editor panes. But the first Error is now ok.

But The Error "init.coffee:61 Uncaught TypeError: Cannot read property 'getSession' of null" is still here.

**Comment by dev-rke** [comment] 2016-05-02 23:13
New version 0.1.3 is released, i really hope i got all potential issues.
They changed some parts of the codiad core, which do now behave a bit different.
The bad thing is that i need to access the event handler of the ace editor to keep track for content changes, so i need to look up the currently used editor session multiple times.

Please give me some feedback if it works or not, so i can hopefully close this ticket this time. :-)

**Comment by ghost** [comment] 2016-05-03 07:37
Ok, now it is fixed!

Thank you very much!

**Closed by ghost** 2016-05-03 07:37 UTC

**Comment by dev-rke** [comment] 2016-05-05 18:06
Best news today. :-)
